/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author 182310075
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBCliente = new javax.swing.JButton();
        jBComplemento = new javax.swing.JButton();
        jBProduto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 415));
        setMinimumSize(new java.awt.Dimension(400, 415));
        getContentPane().setLayout(null);

        jBCliente.setBackground(new java.awt.Color(91, 195, 241));
        jBCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBCliente.setForeground(new java.awt.Color(231, 208, 61));
        jBCliente.setText("Cliente");
        jBCliente.setToolTipText("");
        jBCliente.setBorder(null);
        jBCliente.setBorderPainted(false);
        jBCliente.setContentAreaFilled(false);
        jBCliente.setDefaultCapable(false);
        jBCliente.setFocusPainted(false);
        jBCliente.setFocusable(false);
        jBCliente.setRequestFocusEnabled(false);
        jBCliente.setVerifyInputWhenFocusTarget(false);
        jBCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jBCliente);
        jBCliente.setBounds(40, 20, 70, 20);

        jBComplemento.setBackground(new java.awt.Color(91, 195, 241));
        jBComplemento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBComplemento.setForeground(new java.awt.Color(231, 208, 61));
        jBComplemento.setText("Complemento");
        jBComplemento.setBorder(null);
        jBComplemento.setBorderPainted(false);
        jBComplemento.setContentAreaFilled(false);
        jBComplemento.setDefaultCapable(false);
        jBComplemento.setFocusPainted(false);
        jBComplemento.setFocusable(false);
        jBComplemento.setRequestFocusEnabled(false);
        jBComplemento.setVerifyInputWhenFocusTarget(false);
        jBComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBComplementoActionPerformed(evt);
            }
        });
        getContentPane().add(jBComplemento);
        jBComplemento.setBounds(120, 20, 120, 20);

        jBProduto.setBackground(new java.awt.Color(91, 195, 241));
        jBProduto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBProduto.setForeground(new java.awt.Color(231, 208, 61));
        jBProduto.setText("Produto");
        jBProduto.setBorder(null);
        jBProduto.setBorderPainted(false);
        jBProduto.setContentAreaFilled(false);
        jBProduto.setDefaultCapable(false);
        jBProduto.setFocusPainted(false);
        jBProduto.setFocusable(false);
        jBProduto.setRequestFocusEnabled(false);
        jBProduto.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jBProduto);
        jBProduto.setBounds(250, 20, 70, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Açai TED.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(480, 480));
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 420));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -10, 400, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBClienteActionPerformed
        // TODO add your handling code here:
        ClienteView c = new ClienteView();
        c.setVisible(true);
    }//GEN-LAST:event_jBClienteActionPerformed

    private void jBComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBComplementoActionPerformed
        // TODO add your handling code here:
        ComplementoView com = new ComplementoView();
        com.setVisible(true);

    }//GEN-LAST:event_jBComplementoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCliente;
    private javax.swing.JButton jBComplemento;
    private javax.swing.JButton jBProduto;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
